# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "18.220.4.39"
fast_sync = true

db_backend = "memdb"
log_level = "mempool:error,*:debug"


[rpc]
laddr = "tcp://0.0.0.0:46657"


[mempool]
recheck = false
broadcast = false
wal_dir = ""

[consensus]
max_block_size_txs = 10000
create_empty_blocks = false
timeout_propose = 10000
skip_timeout_commit = true
timeout_commit = 1
wal_light = true
block_part_size = 262144
create_empty_blocks_interval = 60


[p2p]
max_num_peers = 300
pex = true
max_msg_packet_payload_size=65536
send_rate=51200000 # 50 MB/s
recv_rate=51200000 # 50 MB/s
laddr = "tcp://0.0.0.0:46656"
seeds = "18.216.189.98:46656,18.217.150.101:46656"
