# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "165.227.97.165"
fast_sync = true

db_backend = "leveldb"
log_level = "state:info,*:error"
#log_level = "*:debug"


[rpc]
laddr = "tcp://0.0.0.0:46657"


[consensus]
create_empty_blocks_interval = 60


[p2p]
max_num_peers = 300
laddr = "tcp://0.0.0.0:46656"
seeds = "95.85.6.217:46656,138.197.184.11:46656,178.62.78.26:46656"
