# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "188.226.176.16"
fast_sync = true

db_backend = "leveldb"
log_level = "state:info,*:error"
#log_level = "*:debug"


[rpc]
laddr = "tcp://0.0.0.0:46657"


[consensus]
create_empty_blocks_interval = 10


[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "138.197.98.247:46656,46.101.208.223:46656,138.68.134.218:46656"
