# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "95.85.4.244"
fast_sync = true
db_backend = "leveldb"
log_level = "debug"

[rpc]
laddr = "tcp://0.0.0.0:46657"

[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "mercury-node0.testnets.interblock.io:46656,mercury-node1.testnets.interblock.io:46656,mercury-node2.testnets.interblock.io:46656,mercury-node3.testnets.interblock.io:46656,mercury-node4.testnets.interblock.io:46656,mercury-node5.testnets.interblock.io:46656,mercury-node6.testnets.interblock.io:46656"
