# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "13.59.161.37"
fast_sync = true
db_backend = "leveldb"
log_level = "debug"

[rpc]
laddr = "tcp://0.0.0.0:46657"

[mempool]
recheck = false

[consensus]
max_block_size_txs = 1000
create_empty_blocks = false
#timeout_propose = 10000

[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "52.14.116.70:46656,52.15.72.244:46656"
