# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "18.220.115.169"
fast_sync = true
db_backend = "leveldb"
log_level = "debug"

[rpc]
laddr = "tcp://0.0.0.0:46657"

[mempool]
recheck = false

[consensus]
max_block_size_txs = 10000
create_empty_blocks = false
#timeout_propose = 10000
skip_timeout_commit = true

[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "18.220.89.250:46656,18.220.4.214:46656,18.221.7.33:46656,13.59.228.61:46656,52.15.147.225:46656"
