# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "18.221.10.172"
fast_sync = true
db_backend = "leveldb"
log_level = "debug"

[rpc]
laddr = "tcp://0.0.0.0:46657"

[mempool]
recheck = false

[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "18.221.10.154:46656,18.221.10.51:46656"
