# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "52.14.218.145"
fast_sync = true
db_backend = "memdb"
#log_level = "mempool:error,*:debug"
log_level = "state:info,*:error"

[rpc]
laddr = "tcp://0.0.0.0:46657"

[mempool]
recheck = false
broadcast = false
wal_dir = ""

[consensus]
max_block_size_txs = 10000
create_empty_blocks = false
timeout_propose = 10000
skip_timeout_commit = true
timeout_commit = 1
wal_light = true
block_part_size = 262144

[p2p]
max_msg_packet_payload_size=65536
send_rate=51200000 # 50 MB/s
recv_rate=51200000 # 50 MB/s
laddr = "tcp://0.0.0.0:46656"
seeds = "52.15.35.44:46656,52.14.22.180:46656,13.58.34.247:46656,18.221.61.141:46656,18.221.47.183:46656"
