# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "52.14.144.42"
fast_sync = true
db_backend = "leveldb"
log_level = "debug"

[rpc]
laddr = "tcp://0.0.0.0:46657"

[mempool]
recheck = false

[consensus]
max_block_size_txs = 10000
create_empty_blocks = false
#timeout_propose = 10000
skip_timeout_commit = true

[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "18.220.247.204:46656,18.221.7.76:46656,52.14.247.8:46656,52.15.165.211:46656,52.14.79.161:46656"
