# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "159.203.99.115"
fast_sync = true
db_backend = "memdb"
#log_level = "mempool:error,*:debug"
log_level = "state:info,*:error"

[rpc]
laddr = "tcp://0.0.0.0:46657"

#[mempool]
#recheck = false
#broadcast = false
#wal_dir = ""

[consensus]
#max_block_size_txs = 10000
#create_empty_blocks = false
#timeout_propose = 10000
#skip_timeout_commit = true
#timeout_commit = 1
#wal_light = true
#block_part_size = 262144
create_empty_blocks_interval = 1

[p2p]
#max_msg_packet_payload_size=65536
#send_rate=51200000 # 50 MB/s
#recv_rate=51200000 # 50 MB/s
laddr = "tcp://0.0.0.0:46656"
seeds = "128.199.127.44:46656,138.68.16.197:46656,178.62.86.11:46656,159.203.27.63:46656,46.101.181.61:46656,192.81.221.89:46656"
