# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "188.166.234.188"
fast_sync = true
db_backend = "memdb"
#log_level = "mempool:error,*:debug"
log_level = "state:info,*:error"

[rpc]
laddr = "tcp://0.0.0.0:46657"

[mempool]
recheck = false
broadcast = false
wal_dir = ""

[consensus]
max_block_size_txs = 10000
create_empty_blocks = false
timeout_propose = 10000
skip_timeout_commit = true
timeout_commit = 1
wal_light = true
block_part_size = 262144

[p2p]
max_msg_packet_payload_size=65536
send_rate=51200000 # 50 MB/s
recv_rate=51200000 # 50 MB/s
laddr = "tcp://0.0.0.0:46656"
seeds = "138.197.155.56:46656,159.203.121.82:46656,82.196.15.25:46656,138.68.93.32:46656,138.197.200.110:46656,178.62.114.200:46656"
