# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "138.68.148.10"
fast_sync = true

db_backend = "leveldb"
log_level = "state:info,*:error"
#log_level = "*:debug"


[rpc]
laddr = "tcp://0.0.0.0:46657"


[consensus]
create_empty_blocks_interval = 60


[p2p]
max_num_peers = 300
laddr = "tcp://0.0.0.0:46656"
seeds = "146.185.161.67:46656,46.101.182.76:46656,104.236.223.21:46656"
