# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "174.138.62.113"
fast_sync = true

db_backend = "leveldb"
log_level = "state:info,*:error"


[rpc]
laddr = "tcp://0.0.0.0:46657"


[consensus]
create_empty_blocks_interval = 1


[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "46.101.212.80:46656,139.59.171.109:46656,95.85.23.48:46656"
