# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "146.185.134.56"
fast_sync = true

db_backend = "leveldb"
log_level = "state:info,*:error"


[rpc]
laddr = "tcp://0.0.0.0:46657"


[consensus]
create_empty_blocks_interval = 1


[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "178.62.105.57:46656,159.203.162.103:46656,46.101.207.142:46656"
