# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "104.236.86.110"
fast_sync = true

db_backend = "leveldb"
log_level = "state:info,*:error"


[rpc]
laddr = "tcp://0.0.0.0:46657"


[consensus]
create_empty_blocks_interval = 1


[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "188.226.131.178:46656,178.62.116.245:46656,165.227.171.83:46656"
