# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "YOURNAME"
fast_sync = true

db_backend = "leveldb"
log_level = "state:info,*:error"

[rpc]
laddr = "tcp://0.0.0.0:46657"

[consensus]
create_empty_blocks_interval = 60

[tx_index]
index_all_tags = true

[p2p]
max_num_peers = 300
pex = true
laddr = "tcp://0.0.0.0:46656"
# IPs: Adrian1, Adrian2, Nickray, Michael, Zaki, Sunny, Tony
seeds = "67.207.78.91:46656,165.227.246.236:46656,gaia-3002.h.valid.st:46656,172.31.28.156:46656,35.204.86.158:46656,148.76.42.147:46656,104.198.227.222:46656"
