# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "165.227.161.132"
fast_sync = true

db_backend = "leveldb"
log_level = "state:info,*:error"
#log_level = "*:debug"


[rpc]
laddr = "tcp://0.0.0.0:46657"


[consensus]
create_empty_blocks_interval = 10


[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "178.62.99.111:46656,104.236.26.255:46656,95.85.51.98:46656"
