# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "165.227.216.141"
fast_sync = true

db_backend = "leveldb"
log_level = "state:info,*:error"
#log_level = "*:debug"


[rpc]
laddr = "tcp://0.0.0.0:46657"


[consensus]
create_empty_blocks_interval = 60

[tx_index]
index_all_tags = true


[p2p]
max_num_peers = 300
pex = true
laddr = "tcp://0.0.0.0:46656"
seeds = "178.62.54.239:46656,37.139.15.9:46656,46.101.213.35:46656"
