# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "82.196.10.209"
fast_sync = true

db_backend = "leveldb"
log_level = "state:info,*:error"


[rpc]
laddr = "tcp://0.0.0.0:46657"


[consensus]
create_empty_blocks_interval = 1


[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "178.62.11.154:46656,104.131.125.225:46656,139.59.139.111:46656"
